### ISSUE TITLE
Certain datu8 files won't extract at all

### ISSUE THREAD

**Issue by DSwizzy** [koukdw/Aquarium_tools#2]
I'm working on a MUSICUS! uncensored/restore mod for the Nintendo Switch version of the game, and particular these files won't create a .txt file after running the dump.py executable:

cgmode.datu8

configstring.datu8

eventgroup.datu8

eventmode.datu8

keycommand.datu8

mascot.datu8

mascotvoice.datu8

musicmode.datu8

replaymode.datu8

scene.datu8

standpos.datu8

systemvoice.datu8

trophy.datu8

voicetab.datu8

**Comment by koukdw** [comment]
There are files that don't have any text in them just values. So i don't create them.

**Comment by DSwizzy** [comment]
> There are files that don't have any text in them just values. So i don't create them. All the files you mentioned are of this type. If you are still unsure you can download a hex editor and configure it to show utf8 text. If you find that there's still a mistake. Tell me the file and i'll investigate.

Ah okay, it's my first time using something like this so i wasn't aware how it worked, thank you very much for the information!

**Comment by koukdw** [comment]
I'm not sure what you mean, you don't need to convert anything.
Just dump the text with the script once you've done your modification to the txt files, run the datu8_import script

**Comment by DSwizzy** [comment]
> I'm not sure what you mean, you don't need to convert anything. Just dump the text with the script once you've done your modification to the txt files, run the datu8_import script

oh alright, thank you very much once again
