### ISSUE TITLE
Help request!

### ISSUE THREAD

**Issue by Cosetto** [koukdw/Aquarium_tools#3]
Hi there, I wonder if you can help me with another game's scripts? It's also Nexas engine [vndb link](https://vndb.org/v24702). I tried to mod between your modified code and the original one from Niflheim. The dump.py worked well, but the insert.py didn't, the game crashed every time. I'll include the code and scripts here
[script.zip](https://github.com/koukdw/Aquarium_tools/files/11554130/script.zip)

**Comment by Cosetto** [comment]
Ah, it worked somehow, looks like I need the tbl.txt in order to insert. But I wonder if I can insert text without it. Oh well

**Comment by kdw-code** [comment]
You should try the scripts https://github.com/masagrator/NXGameScripts/tree/main/Aonatsu%20Line there it's a bit more advanced than my script where i just extract the text.

**Comment by Cosetto** [comment]
Thanks, but I don't think that one is for window version since the extension is ".binu8"

> D:\Aonatsu\test\Unpacked>Script_disassembler.py Script
> 00共通01
> 437
> String size check failed! Expected: 2412088575, got 21
> Offset: 0x1f8ec
> 奄ﾉ戻りました

**Comment by kdw-code** [comment]
Ah right i wasnt sure which version you needed

**Comment by Cosetto** [comment]
> Ah right i wasnt sure which version you needed

It was for window version, actually.
