### ISSUE TITLE
struct error when working with Kemonomichi * Girlish Square binu8 files

### ISSUE THREAD

**Issue by Qiangong2** [koukdw/Aquarium_tools#6]
Hi!

This may be outside the purview of these tools, but I'm trying to extract the binu8 files for the game Kemonomichi * Girlish Square. However, whenever I try to extract the files, I receive the following:

```
Traceback (most recent call last):
  File "/Users/macbook/Downloads/Aquarium_tools/binu8_dump.py", line 66, in <module>
    main()
    ~~~~^^
  File "/Users/macbook/Downloads/Aquarium_tools/binu8_dump.py", line 56, in main
    str_count = byte2int(src.read(4))
  File "/Users/macbook/Downloads/Aquarium_tools/binu8_dump.py", line 17, in byte2int
    long_tuple=struct.unpack('=L',byte)
struct.error: unpack requires a buffer of 4 bytes
```

I've extracted the romfs through ryujinx and I don't think they're corrupted or anything since the files (images, audio, etc.) are all valid.

Here are the script and config folders for reference:
[Script.zip](https://github.com/user-attachments/files/17622490/Script.zip)
[Config.zip](https://github.com/user-attachments/files/17622494/Config.zip)

**Comment by kdw-code** [comment]
Yeah don't worry it's not your file it's just my code that don't handle newer games because they added a string for the version at the top of the file and other stuff. i'll make a quick version for you but i don't intend to really update that script. If i either do something with this it will be a new tool that do more stuff.

**Comment by kdw-code** [comment]
@Qiangong2 It's done, for Configs i need to update the code too, it would be nicer to dump a csv but that will take some time so i'll just update so it works for now

**Comment by Qiangong2** [comment]
@koukdw Thanks for working on it so quickly! I can now extract and edit the text successfully. However, the game freezes on a black screen when I try to load translated text as a romfs mod. Is this due to the Configs issue?

Also, it seems to be duplicating the text (example attached), but I'm not sure if that's supposed to happen or not.

[k_02colonobuzixekutoanimeshuuryougozidousakujosasetai.txt](https://github.com/user-attachments/files/17669549/k_02colonobuzixekutoanimeshuuryougozidousakujosasetai.txt)

**Comment by kdw-code** [comment]
The freeze is weird can you post a screenshot of your folder setup for the romfs, you shouldn't use the config dumper yet since it isn't updated to handle the new types that the new engine version support.

The text duplicate is normal the line with the empty dots is **original line**, the line with filled dots is **the line you modify**.

Send me the modified files too that way i can verify if it's actually my program or if it's a user mistake.

**Comment by hpckurt** [comment]
Here's what I see when launching the game with an edited binu8:

![kemo](https://github.com/user-attachments/assets/c6137180-7cc0-4bcc-9bb0-da2ac725f590)

It should be loading the first screen, but it freezes instead (well, it doesn't freeze, it just fails to load).

Edited binu8: [maho1_01.binu8.zip](https://github.com/user-attachments/files/17682463/maho1_01.binu8.zip)
Original: [maho1_01.binu8-original.zip](https://github.com/user-attachments/files/17682468/maho1_01.binu8-original.zip)
Edited text file: [maho1_01.txt](https://github.com/user-attachments/files/17682476/maho1_01.txt)

I only changed one line in the text file.

Here is my file tree:
<img width="754" alt="Screenshot 2024-11-08 at 10 10 22 AM" src="https://github.com/user-attachments/assets/f6bee9d3-e41b-4b43-94d4-2d7898ff7d91">

I don't think there's any issues with the file locations though since the game only fails to load when it reaches the binu8.

**Comment by Qiangong2** [comment]
Here's what I see when launching the game with an edited binu8:

![kemo](https://github.com/user-attachments/assets/c6137180-7cc0-4bcc-9bb0-da2ac725f590)

It should be loading the first screen, but it freezes instead (well, it doesn't freeze, it just fails to load).

Edited binu8: [maho1_01.binu8.zip](https://github.com/user-attachments/files/17682463/maho1_01.binu8.zip)
Original: [maho1_01.binu8-original.zip](https://github.com/user-attachments/files/17682468/maho1_01.binu8-original.zip)
Edited text file: [maho1_01.txt](https://github.com/user-attachments/files/17682476/maho1_01.txt)

I only changed one line in the text file.

Here is my file tree:
<img width="754" alt="Screenshot 2024-11-08 at 10 10 22 AM" src="https://github.com/user-attachments/assets/f6bee9d3-e41b-4b43-94d4-2d7898ff7d91">

I don't think there's any issues with the file locations though since the game only fails to load when it reaches the binu8.

**Comment by kdw-code** [comment]
I confirm there's a problem i might have made a mistake, i'll fix that tomorrow i pretty much have the .datu8 reader/writer ready too. I want to rewrite the string dumper/importer as well it's a good opportunity.

**Comment by kdw-code** [comment]
Wait mine is correct when i do the same thing.
[maho1_01.zip](https://github.com/user-attachments/files/17683729/maho1_01.zip)

But yours have random null bytes after the length

**Comment by kdw-code** [comment]
Mine
![image](https://github.com/user-attachments/assets/b8fe7323-8521-48a8-ab15-80f2a32d084e)
Yours
![image](https://github.com/user-attachments/assets/98a55fb0-dccb-4283-8ef6-f2b7545b9694)

**Comment by Qiangong2** [comment]
That's really odd. I haven't touched anything related to the length. Could it be because I'm running it on macOS?

**Comment by kdw-code** [comment]
I don't really know. Try redumping and redoing the modification while being careful to just change what is between the bracket

**Comment by kdw-code** [comment]
Ok i know why i think i'll try to fix it later.
edit: Try redownloading the binu8_import script it should work now.

It's only a temporary fix i really need to rewrite that script it's a mess.
Basically 2 years ago i forgot to add a '<' before the 'L' to `dst.write(struct.pack('L', len(str)+1))`
Because of this i'm writing a native long type which has a different size depending on the platform. On mac it's 8 bytes and on windows it's 4 bytes so thats why you have 4 random bytes added.

**Comment by Qiangong2** [comment]
~~So I get the same issue, even after going so far as to re-dump the romfs. Yours does work though.~~

~~I also tried on a windows arm64 vm and it makes a valid file. It seems to be related specifically to macOS since Python 3.11, 3.12, and 3.13 all have the same issue, but 3.11 makes a valid file on windows 11 arm.~~

Ah, that was the fix! Thanks a bunch! It's working now 😄

**Comment by kdw-code** [comment]
Yeah sorry for the trouble, i wrote that script when i didn't have much programming skill, i'm still not that good but i know better now x)

**Comment by Qiangong2** [comment]
No worries! Mac isn't usually a supported environment for translation tools, so I'm just happy it's working at all. Also, you're still way better at programming than me >_<

One question, do you have tips for line-wrapping? For instance, the game doesn't care about it one bit lol:

<img width="859" alt="Screenshot 2024-11-08 at 2 49 51 PM" src="https://github.com/user-attachments/assets/1db42752-8198-4a7a-8ce6-11ad4f3119fa">

**Comment by kdw-code** [comment]
This engine doesn't have line wrapping. It either need a patch or you need to manually  add '@n' character where you want the line to break

**Comment by kdw-code** [comment]
There's a bunch of characters like that.

**Comment by kdw-code** [comment]
Here is an uncomplete list. Some codes have argument, it's probably better if you observe how the japanese script use them.
```
"@n" => NEW_LINE
"@p" => PAUSE
"@s" => FONT_SIZE
"@i" => FONT_COLOR
"@m" => TEXT_DISP_SPEED
"@f" => TEXT_FADE_TIME
"@c" => TEXT_CENTER
"@o" => VOICE_VOLUME
"@w" => WAIT
"@t" => VOICE_WAIT
"@v" => VOICE
"@h" => FACE_TYPE
"@r" => RUBY
"@k" => NO_KEY_WAIT
"@e" => NO_KEY_WAIT_E
"@a" => FORCE_AUTO
"@g" => GAIJI
"@d" => TEXT_NO_DISP
"@l" => VOICE_OVER_PLAY
"@@" => ESCAPE
```

**Comment by Qiangong2** [comment]
Hi @koukdw Just wanted to check and see if you were able to figure out the data dumping issue? The text extraction and patching works great, but that unfortunately doesn't work with the menus. No pressure or anything though, I'm still working on translating the story 🙂

**Edit:** Also, there are some \*ahem\* _cultured_ scenes in the PC release that weren't included (for obvious reasons) in the switch release. Is it possible to add them to the switch version (as long as the audio and images are converted to the right format)?

For example, in the all-ages version, the scenario text files jump from `maho1_15` to `maho1_17`, but in the PC release, there's a `maho1_16h` file it jumps to in between. The voices and images are entirely separate, so there's zero overlap.

Ultimately, it's not a huge loss if the scenes can't be integrated (the story doesn't rely on them like other VNs can), but it'd be nice to make a "definitive edition" if it was possible.

**Comment by kdw-code** [comment]
@Qiangong2 Not sure what you mean by menu, Menu are just images, you need to use an image editing software for that. The only thing that isn't images (mouse over help text) are located in dat files or lgnt files depending on how old is the game.

Adding the H scenes isn't possible with current tools, you need to do way more than just adding images and sound. You need a decompiler/compiler and also a way to create those spm files (spritesheet for different expression) which is not something i have enough skill to accomplish. It's possible, i've published enough research for it for the script format and spm format is fully documented in aonatsu line chinese demo but not by me.

**Comment by Qiangong2** [comment]
> [@Qiangong2](https://github.com/Qiangong2) Not sure what you mean by menu, Menu are just images, you need to use an image editing software for that. The only thing that isn't images (mouse over help text) are located in dat files or lgnt files depending on how old is the game.
> 
> Adding the H scenes isn't possible with current tools, you need to do way more than just adding images and sound. You need a decompiler/compiler and also a way to create those spm files (spritesheet for different expression) which is not something i have enough skill to accomplish. It's possible, i've published enough research for it for the script format and spm format is fully documented in aonatsu line chinese demo but not by me.

Ah, alright. Thanks for the explanation! One of the reasons that I asked is that almost all of the H scene audio was left in the switch version by Entergram. At least with Kemonomichi * Girlish Square, all the spritesheets are actually PNG files in the switch version. On the PC version, they are spm files.

As an aside, your `datau8_dump` tool _does_ work! It only works though on some files. It seems like it fails if a datau8 file doesn't actually use utf-8.

**Comment by kdw-code** [comment]
That's incorrect there's spm files in both games. the spritesheet png isnt enough, the game also need to know the position of all the element and where to put them on the screen which is what the spm file contain (it also contains way more stuff actually).

datu8_dump is old i wont update it, use the main.py in the tools folder it's way more powerful it convert everything to csv in the format (type, value). It also support all the different encoding/string format
